### ISSUE TITLE
Can't find Sorcar OSC inputs

### ISSUE THREAD

**Issue by billyberkouwer** [maybites/blender.NodeOSC#9]
Hi there,

I've just discovered your plugin. It appears to offer what I need for an upcoming collaboration with an electronic music producer. I am very new to OSC but I work frequently with Blender and Javascript (although in Blender I rarely work with Sorcar and Animation nodes)t. For the moment, I'm familiarising myself with Sorcar and Animation Nodes, before I move onto the OSC side of things. In my experiments, I have found the OSC inputs available within Animation Nodes but can't seem to find them within Sorcar. Manipulating meshes is my main aim with the project so, for me, Sorcar is more suitable.

I'm running Blender 2.91 with the latest version of NodeOSC and Sorcar.

Apologies for the basic question! Since I couldn't find a solution thru the YT video or wiki, I thought I'd ask you direct.

Great what you're doing with this plugin, I see a load of potential with it! Being able to control PSDFs in future would be amazing.

Cheers,

Billy

**Comment by maybites** [comment]
Hi Billy

To be honest, the name 'NodeOSC' is nowadays a bit misleading, since I will not further develop explicit osc nodes anymore. It is not necessary anymore, I actually would discourage it. I probably should rename this plugin..

It is better to use the new right-click-context function 'create a node osc handler' when hovering over the node-value you want to control. This should work with all types of nodes.

what are PSDFs?

cheers

martin
